acl "trusted" {
    localhost;
    localnets;
    192.168.0.0/16;
    2001:ee0:d743::/48;
};

options {
    directory "/var/bind";
    listen-on { any; };
    listen-on-v6 { any; };
    allow-query { trusted; };
    allow-query-cache { trusted; };
    allow-recursion { trusted; };
    recursion yes;
	dnssec-validation auto;
    max-ncache-ttl 3600;
    prefetch 2 9;
    minimal-responses yes;

    response-policy {
        zone "oisd.rpz";
        zone "hagezi.pro.plus.rpz";
        zone "hagezi.tif.rpz";
    };
};

zone "." IN {
    type hint;
    file "named.ca";
};

zone "localhost" IN {
    type master;
    file "localhost.zone";
};

zone "127.in-addr.arpa" IN {
    type master;
    file "127.in-addr.arpa.zone";
};

// RPZ Zones
zone "oisd.rpz" {
    type master;
    file "/etc/bind/oisd.rpz";
    allow-query { localhost; };
};

zone "hagezi.pro.plus.rpz" {
    type master;
    file "/etc/bind/hagezi.pro.plus.rpz";
    allow-query { localhost; };
};

zone "hagezi.tif.rpz" {
    type master;
    file "/etc/bind/hagezi.tif.rpz";
    allow-query { localhost; };
};
