options {
    directory "/var/bind";
    listen-on { any; };
    allow-query { any; };
    recursion yes;
    dual-stack-servers { any; };

    response-policy {
        zone "oisd.rpz";
        zone "hagezi.pro.plus.rpz";
        zone "hagezi.tif.rpz";
    };
};

zone "." IN {
    type hint;
    file "named.ca";
};

zone "localhost" IN {
    type master;
    file "localhost.zone";
};

zone "127.in-addr.arpa" IN {
    type master;
    file "127.in-addr.arpa.zone";
};

// RPZ Zones
zone "oisd.rpz" {
    type master;
    file "/etc/bind/oisd.rpz";
    allow-query { localhost; };
};

zone "hagezi.pro.plus.rpz" {
    type master;
    file "/etc/bind/hagezi.pro.plus.rpz";
    allow-query { localhost; };
};

zone "hagezi.tif.rpz" {
    type master;
    file "/etc/bind/hagezi.tif.rpz";
    allow-query { localhost; };
};
